

// FieldValidationRule Actions
export const GET_ALL_FIELDVALIDATIONRULES_REQUEST = 'GET_ALL_FIELDVALIDATIONRULES_REQUEST';
export const GET_ALL_FIELDVALIDATIONRULES_SUCCESS = 'GET_ALL_FIELDVALIDATIONRULES_SUCCESS';
export const GET_ALL_FIELDVALIDATIONRULES_FAILURE = 'GET_ALL_FIELDVALIDATIONRULES_FAILURE';

export const GET_FIELDVALIDATIONRULE_REQUEST = 'GET_FIELDVALIDATIONRULE_REQUEST';
export const GET_FIELDVALIDATIONRULE_SUCCESS = 'GET_FIELDVALIDATIONRULE_SUCCESS';
export const GET_FIELDVALIDATIONRULE_FAILURE = 'GET_FIELDVALIDATIONRULE_FAILURE';

export const UPSERT_FIELDVALIDATIONRULE_REQUEST = 'UPSERT_FIELDVALIDATIONRULE_REQUEST';
export const UPSERT_FIELDVALIDATIONRULE_SUCCESS = 'UPSERT_FIELDVALIDATIONRULE_SUCCESS';
export const UPSERT_FIELDVALIDATIONRULE_FAILURE = 'UPSERT_FIELDVALIDATIONRULE_FAILURE';

export const DELETE_FIELDVALIDATIONRULE_REQUEST = 'DELETE_FIELDVALIDATIONRULE_REQUEST';
export const DELETE_FIELDVALIDATIONRULE_SUCCESS = 'DELETE_FIELDVALIDATIONRULE_SUCCESS';
export const DELETE_FIELDVALIDATIONRULE_FAILURE = 'DELETE_FIELDVALIDATIONRULE_FAILURE';


// FormBuilder Actions
export const GET_FORMBUILDER_REQUEST = 'GET_FORMBUILDER_REQUEST';
export const GET_FORMBUILDER_SUCCESS = 'GET_FORMBUILDER_SUCCESS';
export const GET_FORMBUILDER_FAILURE = 'GET_FORMBUILDER_FAILURE';

export const GET_FORMBUILDER_BY_ID_REQUEST = 'GET_FORMBUILDER_BY_ID_REQUEST';
export const GET_FORMBUILDER_BY_ID_SUCCESS = 'GET_FORMBUILDER_BY_ID_SUCCESS';
export const GET_FORMBUILDER_BY_ID_FAILURE = 'GET_FORMBUILDER_BY_ID_FAILURE';

export const UPSERT__FORMBUILDER_REQUEST = 'UPSERT__FORMBUILDER_REQUEST';
export const UPSERT__FORMBUILDER_SUCCESS = 'UPSERT__FORMBUILDER_SUCCESS';
export const UPSERT__FORMBUILDER_FAILURE = 'UPSERT__FORMBUILDER_FAILURE';

export const DELETE_FORMBUILDER_REQUEST = 'DELETE_FORMBUILDER_REQUEST';
export const DELETE_FORMBUILDER_SUCCESS = 'DELETE_FORMBUILDER_SUCCESS';
export const DELETE_FORMBUILDER_FAILURE = 'DELETE_FORMBUILDER_FAILURE';


// ClientFormBuilderHeaderMapping
export const INSERT_CLIENT_FORM_BUILDER_HEADER_MAPPING_REQUEST = 'INSERT_CLIENT_FORM_BUILDER_HEADER_MAPPING_REQUEST';
export const INSERT_CLIENT_FORM_BUILDER_HEADER_MAPPING_SUCCESS = 'INSERT_CLIENT_FORM_BUILDER_HEADER_MAPPING_SUCCESS';
export const INSERT_CLIENT_FORM_BUILDER_HEADER_MAPPING_FAILURE = 'INSERT_CLIENT_FORM_BUILDER_HEADER_MAPPING_FAILURE';

export const DELETE_CLIENT_FORM_BUILDER_HEADER_MAPPING_BY_ID_REQUEST = 'DELETE_CLIENT_FORM_BUILDER_HEADER_MAPPING_BY_ID_REQUEST';
export const DELETE_CLIENT_FORM_BUILDER_HEADER_MAPPING_BY_ID_SUCCESS = 'DELETE_CLIENT_FORM_BUILDER_HEADER_MAPPING_BY_ID_SUCCESS';
export const DELETE_CLIENT_FORM_BUILDER_HEADER_MAPPING_BY_ID_FAILURE = 'DELETE_CLIENT_FORM_BUILDER_HEADER_MAPPING_BY_ID_FAILURE';

export const GET_CLIENT_FORM_BUILDER_HEADER_MAPPINGS_BY_CLIENT_ID_REQUEST = 'GET_CLIENT_FORM_BUILDER_HEADER_MAPPINGS_BY_CLIENT_ID_REQUEST';
export const GET_CLIENT_FORM_BUILDER_HEADER_MAPPINGS_BY_CLIENT_ID_SUCCESS = 'GET_CLIENT_FORM_BUILDER_HEADER_MAPPINGS_BY_CLIENT_ID_SUCCESS';
export const GET_CLIENT_FORM_BUILDER_HEADER_MAPPINGS_BY_CLIENT_ID_FAILURE = 'GET_CLIENT_FORM_BUILDER_HEADER_MAPPINGS_BY_CLIENT_ID_FAILURE';







