

// FieldValidationRule Actions
export const GET_ALL_FIELDVALIDATIONRULES_REQUEST = 'GET_ALL_FIELDVALIDATIONRULES_REQUEST';
export const GET_ALL_FIELDVALIDATIONRULES_SUCCESS = 'GET_ALL_FIELDVALIDATIONRULES_SUCCESS';
export const GET_ALL_FIELDVALIDATIONRULES_FAILURE = 'GET_ALL_FIELDVALIDATIONRULES_FAILURE';

export const GET_FIELDVALIDATIONRULE_REQUEST = 'GET_FIELDVALIDATIONRULE_REQUEST';
export const GET_FIELDVALIDATIONRULE_SUCCESS = 'GET_FIELDVALIDATIONRULE_SUCCESS';
export const GET_FIELDVALIDATIONRULE_FAILURE = 'GET_FIELDVALIDATIONRULE_FAILURE';

export const UPSERT_FIELDVALIDATIONRULE_REQUEST = 'UPSERT_FIELDVALIDATIONRULE_REQUEST';
export const UPSERT_FIELDVALIDATIONRULE_SUCCESS = 'UPSERT_FIELDVALIDATIONRULE_SUCCESS';
export const UPSERT_FIELDVALIDATIONRULE_FAILURE = 'UPSERT_FIELDVALIDATIONRULE_FAILURE';

export const DELETE_FIELDVALIDATIONRULE_REQUEST = 'DELETE_FIELDVALIDATIONRULE_REQUEST';
export const DELETE_FIELDVALIDATIONRULE_SUCCESS = 'DELETE_FIELDVALIDATIONRULE_SUCCESS';
export const DELETE_FIELDVALIDATIONRULE_FAILURE = 'DELETE_FIELDVALIDATIONRULE_FAILURE';

export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';





